version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=   #paste the puid/pgid of the docker user -> "id" command
      - PGID=
    volumes: # modify your filepaths here
      - /my/path/jellyfin/config:/config    
      - /my/path/jellyfin/data/tvseries:/data/tvseries   
      - /my/path/jellyfin/data/movies:/data/movies
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.domain.com`)  # your domain here
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.tls: true
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      traefik.http.routers.jellyfin.tls.certresolver: myresolver
    networks:
      - "traefik"

networks:
  traefik:
    external: true
